// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using willywonkaapi;

namespace willywonkaapi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190620182646_changedDBnameFIX")]
    partial class changedDBnameFIX
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("willywonkaapi.Models.LocationTableStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created_Time");

                    b.Property<string>("ManagerName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("LocationTableName");
                });

            modelBuilder.Entity("willywonkaapi.Models.RecipeTableStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<DateTime>("Created_Time");

                    b.Property<string>("Description");

                    b.Property<int?>("LocationId");

                    b.Property<int?>("LocationTableNameId");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<string>("SKU");

                    b.HasKey("Id");

                    b.HasIndex("LocationTableNameId");

                    b.ToTable("RecipeTableName");
                });

            modelBuilder.Entity("willywonkaapi.Models.RecipeTableStructure", b =>
                {
                    b.HasOne("willywonkaapi.Models.LocationTableStructure", "LocationTableName")
                        .WithMany("RecipeTableName")
                        .HasForeignKey("LocationTableNameId");
                });
#pragma warning restore 612, 618
        }
    }
}
